// <auto-generated />
namespace StoreMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Corrected_Cycles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Corrected_Cycles));
        
        string IMigrationMetadata.Id
        {
            get { return "202003100719286_Corrected_Cycles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
