// <auto-generated />
namespace StoreMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class makingBirthdatenullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(makingBirthdatenullable));
        
        string IMigrationMetadata.Id
        {
            get { return "202003091048257_makingBirthdatenullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
